package axmgc.web.pond

import scala.xml.{Elem => XElem, Node => XNode, NodeSeq => XNodeSeq, Null => XNull, Attribute => XAttr, UnprefixedAttribute => XUAttr}


trait WebSvg extends WebResBind {
	val pthStylIco = fldrPth_styl + FLD_SEP + "icmbg_sty.css"
	val pthStylIcoDem = fldrPth_styl + FLD_SEP + "icmbg_dem.css"
	def getCssResPths : List[String] = List(pthStylIco, pthStylIcoDem)
	val pthIco3290 = fldrPth_ivct + FLD_SEP + "icon_syms_2018_3290.svg"
	val icoNmPrfx = "icon-"
	val svgBaseClzNms = "icon "
	val divOutClzNms = "glyph fs1"
	val divInClzNms = "clearfix pbs"
	private def mkIcoNmFl (tail: String) = icoNmPrfx + tail
	private def mkIcoHref(tail: String) : String = pthIco3290 + "#" + mkIcoNmFl(tail)
	private def mkIcoClzs(tail: String) : String =  svgBaseClzNms + mkIcoNmFl(tail)

	private lazy val myIcnmSrc = new IconNmSrc {}

	def mkDblDivWithSvgIcon(icoTstTl : String) : XElem = {
		val ddsElem =
			<div class="glyph fs1">
				<div class="clearfix pbs">
					<svg class={mkIcoClzs(icoTstTl)}>
						<use xlink:href={mkIcoHref(icoTstTl)}>
						</use>
					</svg>
					<span class="name"> {mkIcoNmFl(icoTstTl)}</span>
				</div>
			</div>
		ddsElem
	}
	def mkManySvgDivs(lst_icoTl : Seq[String]) : Seq[XElem] = {
		val f = lst_icoTl.map(icoTl => mkDblDivWithSvgIcon(icoTl))
		f
	}
	def wrapInDiv(ndLst : Seq[XElem], prntID : String, prntClzs : String) : XElem = {
		<div id={prntID} class={prntClzs}>{ndLst}</div>
	}
	def testNmLst : Seq[String] = myIcnmSrc.someIconNms
	def mkDDSTstBlk : XElem = {
		val icNmSeq = myIcnmSrc.someIconNms
		val icNmCnt = icNmSeq.length

		val pclzs = "grdCnt" // Defined in ictst_grid.css or other.
		val svgDblDivs = mkManySvgDivs(icNmSeq)
		val wrpDv = wrapInDiv(svgDblDivs, "bunchaSVGDvs_01", pclzs)
		wrpDv
	}

	// def lstToNdSq :
}

/*

<head>
    <title>SVG-Ext adapted</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="icombig32/demo-files/demo.css">
    <link rel="stylesheet" href="icombig32/style.css">
    <style>
        .glyph {
            display: inline-block;
            width: 70px;
        }
        .name {
            font-size: 0.2em;
        }
    </style>
</head>
<body>
<header class="bgc1 clearfix">
<div class="mhl">
    <p>SVG Icons - Generated by <a href="https://icomoon.io/app">IcoMoon</a></p><p><strong>Notice</strong>: This demo (along with "symbol-defs.svg" and "svgxuse.js" files) should be <b>hosted on a web server</b> to work properly.</p>
</div>
</header>
    <div class="clearfix mhl ptl">
        <h1 class="mvm mtn fgc1">Grid Size: 32</h1>
        <div class="glyph fs1">
            <div class="clearfix pbs">
                <svg class="icon icon-d_rotation"><use xlink:href="symbol-defs.svg#icon-d_rotation"></use>
 */